[package]
name = "nexa-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
futures = "0.3"
uuid = { version = "1.2", features = ["v4", "serde"] }
nix = { version = "0.27", features = ["process", "signal"] }
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
utoipa = { version = "4.2", features = ["chrono", "uuid"] }
tokio-tungstenite = "0.21"
sysinfo = "0.30"
serde_yaml = "0.9"
once_cell = "1.19.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
criterion = { version = "0.5", features = ["async_tokio"] }
tokio-test = "0.4"
test-log = { version = "0.2", features = ["trace"] }
env_logger = "0.10"
proptest = "1.4"
tempfile = "3.9"
url = "2.5"
rand = { version = "0.8", features = ["small_rng"] }

[features]
default = []
torch = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[[bench]]
name = "cluster_bench"
harness = false

[[bench]]
name = "loadbalancer_bench"
harness = false
