[package]
name = "nexa-utils"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Multi-agent Control Protocol (MCP) Implementation"
license = "MIT"

[workspace]
members = ["."]

[workspace.metadata.cross]
xargo = false

[features]
default = []
torch = ["rust-bert", "tch"]  # Make torch optional

# Target-specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
libc = { version = "0.2", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
core-foundation = "0.9"

# For static linking on Linux
[target.x86_64-unknown-linux-musl.dependencies]
rustls = { version = "0.21", features = ["dangerous_configuration"] }
webpki-roots = "0.25"
rustls-pemfile = "1.0"

[[bin]]
name = "nexa"
path = "src/bin/nexa.rs"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
tokio-tungstenite = { version = "0.20.1", features = ["connect"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
futures = "0.3.30"
async-trait = "0.1.77"
tokio-stream = "0.1.17"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
clap = { version = "4.5.27", features = ["derive"] }
config = { version = "0.15.6", default-features = false, features = ["yaml", "json5", "ron"] }
tungstenite = { version = "0.20", features = ["native-tls"], default-features = false }
dirs = "6.0.0"
rust-bert = { version = "0.23.0", optional = true, default-features = false }
tch = { version = "0.17.0", optional = true, default-features = false }
chrono = { version = "0.4.34", features = ["serde"] }
syn = { version = "2.0", features = ["full", "parsing"] }
ctrlc = { version = "3.4", features = ["termination"] }
sys-info = "0.9.1"
url = "2.5.0"
once_cell = "1.19.0"
utoipa = { version = "4.1", features = ["yaml", "actix_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "5.0", default-features = false }
nix = { version = "0.29.0", features = ["fs", "mman", "signal"] }
thiserror = "1.0.57"
anyhow = "1.0.80"
rand = "0.8.5"
fs2 = "0.4.3"
socket2 = { version = "0.5.5", features = ["all"] }
native-tls = "0.2"

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
cmake = "0.1.53"

[profile.release]
debug = false
strip = "symbols"  # Strip all symbols
opt-level = 3
lto = true    # Enable link-time optimization
codegen-units = 1  # Optimize for size
panic = "abort"  # Remove panic unwinding to reduce binary size

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", default-features = false }
nix = { version = "0.29", features = ["signal"] }
core-foundation = "0.9"
