[package]
name = "nexa-core"
version = "1.1.2"
edition = "2021"
description = "High-performance WebSocket server implementation in Rust"
authors = ["Your Name <your.email@example.com>"]

[[bin]]
name = "nexa"
path = "src/bin/nexa.rs"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.21.0"
tungstenite = "0.21.0"
futures = "0.3.31"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9.34"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.12.1", features = ["v4", "serde"] }
clap = { version = "4.5.27", features = ["derive"] }
sysinfo = "0.30.13"
chrono = { version = "0.4.39", features = ["serde"] }
url = "2.5.4"
utoipa = { version = "4.2.3", features = ["actix_extras"] }
thiserror = "1.0.69"
nix = { version = "0.27.1", features = ["process", "signal"] }
# Added for cluster management
raft = "0.7.0"  # For leader election and consensus
hashring = "0.3.2"  # For consistent hashing
parking_lot = "0.12"  # For efficient locking
dashmap = "5.5.3"  # For concurrent hash maps
tokio-util = { version = "0.7.10", features = ["codec"] }
num_cpus = "1.16"  # For CPU core count
sys-info = "0.9"  # For system information
rand = { version = "0.8", features = ["small_rng"] }
mdns-sd = "0.7.4"  # For node discovery via mDNS
reqwest = { version = "0.11", features = ["json"] }

[dev-dependencies]
tokio-test = "0.4.3"
test-log = { version = "0.2", features = ["trace"] }
proptest = "1.4"
tempfile = "3.10.1"
once_cell = "1.20"
criterion = { version = "0.5", features = ["async_tokio"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"

[[bench]]
name = "cluster_bench"
harness = false

[[bench]]
name = "loadbalancer_bench"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "unwind"
