host: 127.0.0.1
port: 3000
max_connections: 1000
llm:
  providers: []
  timeout_secs: 0
  max_tokens: 0
logging:
  level: info
  file: logs/nexa.log
  console: true
monitoring:
  enabled: true
  detailed_metrics: true
  metrics_interval_secs: 60
  history_size: 1000
  cpu_threshold: 80.0
  memory_threshold: 90.0
  health_check_interval: 30
