[target.aarch64-unknown-linux-musl]

[target.aarch64-unknown-linux-musl.env]
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER = "rust-lld"
RUSTFLAGS = "-C target-feature=+crt-static -C link-arg=-fuse-ld=lld -C link-arg=-Wl,-dead_strip"

[target.x86_64-unknown-linux-musl]
image = "messense/rust-musl-cross:x86_64-musl"

[target.x86_64-unknown-linux-musl.env]
RUSTFLAGS = "-C target-feature=+crt-static"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "CARGO_TERM_COLOR"
] 